"""added bins for notes

Revision ID: 41032f1bb577
Revises: b9dd9bd94aa2
Create Date: 2019-07-08 05:39:26.513508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41032f1bb577'
down_revision = 'b9dd9bd94aa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bin_1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bin_2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bin_3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bin_4',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('note', sa.Column('bin_1_id', sa.Integer(), nullable=True))
    op.add_column('note', sa.Column('bin_2_id', sa.Integer(), nullable=True))
    op.add_column('note', sa.Column('bin_3_id', sa.Integer(), nullable=True))
    op.add_column('note', sa.Column('bin_4_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'note', 'bin_3', ['bin_3_id'], ['id'])
    op.create_foreign_key(None, 'note', 'bin_2', ['bin_2_id'], ['id'])
    op.create_foreign_key(None, 'note', 'bin_1', ['bin_1_id'], ['id'])
    op.create_foreign_key(None, 'note', 'bin_4', ['bin_4_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.drop_column('note', 'bin_4_id')
    op.drop_column('note', 'bin_3_id')
    op.drop_column('note', 'bin_2_id')
    op.drop_column('note', 'bin_1_id')
    op.drop_table('bin_4')
    op.drop_table('bin_3')
    op.drop_table('bin_2')
    op.drop_table('bin_1')
    # ### end Alembic commands ###
