"""empty message

Revision ID: 4b5ec632bd4f
Revises: 
Create Date: 2019-07-09 09:16:54.735161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b5ec632bd4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bin_1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bin_2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bin_3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bin_4',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=64), nullable=True),
    sa.Column('learning_session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['learning_session_id'], ['learning_session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject')
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('question', sa.String(length=128), nullable=True),
    sa.Column('creataed_on', sa.DateTime(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('learning_session_id', sa.Integer(), nullable=True),
    sa.Column('bin_1_id', sa.Integer(), nullable=True),
    sa.Column('bin_2_id', sa.Integer(), nullable=True),
    sa.Column('bin_3_id', sa.Integer(), nullable=True),
    sa.Column('bin_4_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bin_1_id'], ['bin_1.id'], ),
    sa.ForeignKeyConstraint(['bin_2_id'], ['bin_2.id'], ),
    sa.ForeignKeyConstraint(['bin_3_id'], ['bin_3.id'], ),
    sa.ForeignKeyConstraint(['bin_4_id'], ['bin_4.id'], ),
    sa.ForeignKeyConstraint(['learning_session_id'], ['learning_session.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category')
    )
    op.create_index(op.f('ix_note_question'), 'note', ['question'], unique=True)
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=128), nullable=True),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    op.drop_index(op.f('ix_note_question'), table_name='note')
    op.drop_table('note')
    op.drop_table('subject')
    op.drop_table('learning_session')
    op.drop_table('bin_4')
    op.drop_table('bin_3')
    op.drop_table('bin_2')
    op.drop_table('bin_1')
    # ### end Alembic commands ###
