"""added created on date to notes

Revision ID: f194cd726f36
Revises: 7bfdee95aebf
Create Date: 2019-07-09 05:49:25.681423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f194cd726f36'
down_revision = '7bfdee95aebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('creataed_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'creataed_on')
    # ### end Alembic commands ###
